require('dotenv').config();
const db = require('./index');

const seedWords = [
  // ── EASY ──────────────────────────────────────────────────────────────────
  {
    word: 'the',
    ipa: '/ðə/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['ð'],
    phonemic: { tag: 'function-word', detail: 'Definite article; unstressed schwa form /ðə/ before consonants.' },
    syllabic: { tag: 'monosyllabic', detail: 'Single syllable — no syllable boundary.' },
    accentual: { tag: 'unstressed', detail: 'Typically unstressed in a sentence; receives no primary stress.' },
    intonational: { tag: 'neutral', detail: 'No independent intonation contour; part of larger NP.' },
  },
  {
    word: 'ship',
    ipa: '/ʃɪp/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['ʃ', 'ɪ'],
    phonemic: { tag: 'minimal-pair', detail: 'Contrasts with "sheep" /ʃiːp/; short /ɪ/ vs long /iː/ is a common ESL error.' },
    syllabic: { tag: 'monosyllabic', detail: 'CVC structure; single closed syllable.' },
    accentual: { tag: 'stressed', detail: 'Single syllable receives full stress.' },
    intonational: { tag: 'falling', detail: 'Falling intonation when used as an isolated noun.' },
  },
  {
    word: 'bed',
    ipa: '/bɛd/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['ɛ'],
    phonemic: { tag: 'vowel-quality', detail: 'Mid-front /ɛ/; confused with /æ/ (bad) or /ɪ/ (bid) by many learners.' },
    syllabic: { tag: 'monosyllabic', detail: 'CVC; short vowel in a closed syllable.' },
    accentual: { tag: 'stressed', detail: 'Full primary stress on the single syllable.' },
    intonational: { tag: 'falling', detail: 'Falling nuclear tone in isolation or sentence-final position.' },
  },
  {
    word: 'this',
    ipa: '/ðɪs/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['ð', 'ɪ'],
    phonemic: { tag: 'voiced-dental', detail: 'Voiced dental fricative /ð/ is absent in many L1s; often replaced by /d/ or /z/.' },
    syllabic: { tag: 'monosyllabic', detail: 'Single closed syllable CCVC.' },
    accentual: { tag: 'variable', detail: 'Can be stressed (contrastive "THIS one") or unstressed in a phrase.' },
    intonational: { tag: 'neutral', detail: 'Typically part of a larger NP; no independent contour.' },
  },
  {
    word: 'run',
    ipa: '/rʌn/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['r', 'ʌ'],
    phonemic: { tag: 'approximant', detail: 'English /r/ is a retroflex approximant; /ʌ/ is a mid-central-back vowel distinct from /ɑ/ or /ʊ/.' },
    syllabic: { tag: 'monosyllabic', detail: 'CVC closed syllable.' },
    accentual: { tag: 'stressed', detail: 'Full stress on single syllable.' },
    intonational: { tag: 'falling', detail: 'Falling intonation as a verb in isolation.' },
  },
  {
    word: 'four',
    ipa: '/fɔːr/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['f', 'ɔː'],
    phonemic: { tag: 'rhotic-vowel', detail: '/ɔːr/ is an r-coloured vowel; non-rhotic learners may drop the /r/ coda.' },
    syllabic: { tag: 'monosyllabic', detail: 'Single syllable with long vowel.' },
    accentual: { tag: 'stressed', detail: 'Fully stressed in isolation; may reduce in fast speech numerals.' },
    intonational: { tag: 'falling', detail: 'Falling when listing numbers or in isolation.' },
  },

  // ── MEDIUM ────────────────────────────────────────────────────────────────
  {
    word: 'butter',
    ipa: '/ˈbʌt.ər/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['ʌ', 't', 'ər'],
    phonemic: { tag: 'flap-allophone', detail: 'Intervocalic /t/ is realised as a flap [ɾ] in American English; schwa /ər/ in unstressed syllable.' },
    syllabic: { tag: 'disyllabic', detail: 'Two syllables: ˈbʌt.ər — primary stress on first.' },
    accentual: { tag: 'trochaic', detail: 'Strong-weak stress pattern (trochee).' },
    intonational: { tag: 'falling', detail: 'Falling nuclear tone on the stressed syllable in isolation.' },
  },
  {
    word: 'decide',
    ipa: '/dɪˈsaɪd/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['dɪ', 'saɪ'],
    phonemic: { tag: 'diphthong', detail: '/aɪ/ diphthong; unstressed first syllable /dɪ/ often deleted by learners.' },
    syllabic: { tag: 'disyllabic', detail: 'Two syllables: dɪ.ˈsaɪd — stress on second.' },
    accentual: { tag: 'iambic', detail: 'Weak-strong pattern (iamb); first syllable reduced.' },
    intonational: { tag: 'falling', detail: 'Nuclear fall on the stressed /saɪ/ syllable.' },
  },
  {
    word: 'garden',
    ipa: '/ˈɡɑːr.dən/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['ɑː', 'ə'],
    phonemic: { tag: 'open-back', detail: 'Long /ɑː/ in first syllable; unstressed schwa /ə/ in the final syllable.' },
    syllabic: { tag: 'disyllabic', detail: 'ˈɡɑːr.dən — primary stress on first syllable.' },
    accentual: { tag: 'trochaic', detail: 'Strong-weak stress pattern.' },
    intonational: { tag: 'falling', detail: 'Falling nuclear tone on stressed syllable.' },
  },
  {
    word: 'because',
    ipa: '/bɪˈkɒz/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['bɪ', 'ɒ', 'z'],
    phonemic: { tag: 'voiced-fricative', detail: 'Final /z/; /ɒ/ is a short open-back rounded vowel absent in many L1s.' },
    syllabic: { tag: 'disyllabic', detail: 'bɪ.ˈkɒz — stress on second syllable.' },
    accentual: { tag: 'iambic', detail: 'Unstressed first syllable /bɪ/ often reduced further to /bə/.' },
    intonational: { tag: 'rising-falling', detail: 'Often carries a complex tone in mid-clause position.' },
  },
  {
    word: 'together',
    ipa: '/təˈɡɛð.ər/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['ð', 'ɛ', 'ər'],
    phonemic: { tag: 'medial-dental', detail: '/ð/ in medial position; /ɛ/ mid-front vowel; schwa coda /ər/.' },
    syllabic: { tag: 'trisyllabic', detail: 'tə.ˈɡɛð.ər — three syllables, stress on second.' },
    accentual: { tag: 'iambic-extended', detail: 'Weak-strong-weak pattern; primary stress on /ɡɛð/.' },
    intonational: { tag: 'falling', detail: 'Nuclear fall on the stressed syllable.' },
  },
  {
    word: 'important',
    ipa: '/ɪmˈpɔːr.tənt/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['ɪm', 'ɔː', 'r', 'nt'],
    phonemic: { tag: 'nasal-cluster', detail: '/nt/ word-final cluster; /ɔːr/ rhotic vowel; /ɪm/ unstressed onset.' },
    syllabic: { tag: 'trisyllabic', detail: 'ɪm.ˈpɔːr.tənt — three syllables, stress on second.' },
    accentual: { tag: 'secondary', detail: 'Weak-strong-weak; possible secondary stress on first syllable in slow speech.' },
    intonational: { tag: 'falling', detail: 'Main nuclear stress falls on /pɔːr/.' },
  },

  // ── HARD ──────────────────────────────────────────────────────────────────
  {
    word: 'particularly',
    ipa: '/pərˈtɪk.jə.lər.li/',
    level: 'hard',
    source: 'seed',
    reviewed: true,
    targets: ['ə', 'ɪk', 'jə', 'l'],
    phonemic: { tag: 'polysyllabic-reduction', detail: 'Five-syllable word; multiple unstressed schwas; /j/ glide before /ə/.' },
    syllabic: { tag: 'pentasyllabic', detail: 'pər.ˈtɪk.jə.lər.li — five syllables, primary stress on second.' },
    accentual: { tag: 'complex', detail: 'Stress on /tɪk/; remaining syllables all weakly reduced.' },
    intonational: { tag: 'falling', detail: 'Nuclear tone lands on the stressed syllable /tɪk/.' },
  },
  {
    word: 'deteriorate',
    ipa: '/dɪˈtɪər.i.ə.reɪt/',
    level: 'hard',
    source: 'seed',
    reviewed: true,
    targets: ['ɪər', 'i', 'ə', 'reɪ'],
    phonemic: { tag: 'vowel-sequence', detail: 'Adjacent vowel sounds /ɪər.i.ə/ require careful articulation; /reɪ/ diphthong before final /t/.' },
    syllabic: { tag: 'pentasyllabic', detail: 'dɪ.ˈtɪər.i.ə.reɪt — five syllables, stress on second.' },
    accentual: { tag: 'iambic', detail: 'Stress on /tɪər/; multiple unstressed syllables follow.' },
    intonational: { tag: 'falling', detail: 'Nuclear fall on the stressed syllable.' },
  },
  {
    word: 'entrepreneurship',
    ipa: '/ˌɒn.trə.prəˈnɜːr.ʃɪp/',
    level: 'hard',
    source: 'seed',
    reviewed: true,
    targets: ['ɒ', 'ə', 'nɜː', 'ʃ'],
    phonemic: { tag: 'secondary-stress', detail: 'Secondary stress on /ɒn/; primary on /nɜːr/; /ʃɪp/ suffix; multiple schwas.' },
    syllabic: { tag: 'pentasyllabic', detail: 'ˌɒn.trə.prə.ˈnɜːr.ʃɪp — five syllables.' },
    accentual: { tag: 'double-stress', detail: 'Primary stress on /nɜːr/, secondary on /ɒn/ at the onset.' },
    intonational: { tag: 'falling', detail: 'Nuclear tone on the primary-stressed syllable /nɜːr/.' },
  },
  {
    word: 'simultaneously',
    ipa: '/ˌsɪm.əlˈteɪ.ni.əs.li/',
    level: 'hard',
    source: 'seed',
    reviewed: true,
    targets: ['ɪ', 'teɪ', 'ni', 'əs'],
    phonemic: { tag: 'polysyllabic-diphthong', detail: 'Six syllables; /teɪ/ diphthong carries primary stress; multiple vowel reductions.' },
    syllabic: { tag: 'hexasyllabic', detail: 'ˌsɪm.əl.ˈteɪ.ni.əs.li — six syllables.' },
    accentual: { tag: 'double-stress', detail: 'Primary stress on /teɪ/, secondary on /sɪm/.' },
    intonational: { tag: 'falling', detail: 'Nuclear accent on /teɪ/.' },
  },
  {
    word: 'pronunciation',
    ipa: '/prəˌnʌn.siˈeɪ.ʃən/',
    level: 'hard',
    source: 'seed',
    reviewed: true,
    targets: ['ə', 'ʌ', 'eɪ', 'ʃ'],
    phonemic: { tag: 'vowel-shift', detail: 'Common learner error: pronouncing as "pronounciation"; /ʌ/ in second syllable; /eɪ/ nucleus; /ʃ/ before /ən/.' },
    syllabic: { tag: 'pentasyllabic', detail: 'prə.ˌnʌn.si.ˈeɪ.ʃən — five syllables, stress on fourth.' },
    accentual: { tag: 'secondary', detail: 'Secondary stress on /nʌn/, primary on /eɪ/.' },
    intonational: { tag: 'falling', detail: 'Nuclear fall on /eɪ/ syllable.' },
  },
];

const seedPhrases = [
  // ── EASY PHRASES ──────────────────────────────────────────────────────────
  {
    word: 'this is the one',
    ipa: '/ðɪs ɪz ðə wʌn/',
    level: 'easy',
    type: 'phrase',
    source: 'seed',
    reviewed: true,
    targets: ['ð', 'ɪ', 'z'],
    phonemic: { tag: 'dental-chain', detail: 'Two instances of /ð/ (this, the); linking /z/ in "is"; short /ɪ/ in "this".' },
    syllabic: { tag: 'four-word', detail: 'Four monosyllabic words — function words unstressed, "one" receives nuclear stress.' },
    accentual: { tag: 'end-focus', detail: 'Primary stress on "one"; "this", "is", "the" all weakly reduced.' },
    intonational: { tag: 'falling', detail: 'Falling nuclear tone on "one" as a statement.' },
  },
  {
    word: 'run to the ship',
    ipa: '/rʌn tə ðə ʃɪp/',
    level: 'easy',
    type: 'phrase',
    source: 'seed',
    reviewed: true,
    targets: ['r', 'ʌ', 'ð', 'ʃ', 'ɪ'],
    phonemic: { tag: 'multi-target', detail: 'Combines /r/, /ʌ/, /ð/, /ʃ/, /ɪ/ — four common ESL error phonemes in one phrase.' },
    syllabic: { tag: 'four-word', detail: '"run" and "ship" are stressed; "to" and "the" reduced to /tə/ and /ðə/.' },
    accentual: { tag: 'end-focus', detail: 'Primary nucleus on "ship"; "run" receives secondary stress.' },
    intonational: { tag: 'falling', detail: 'Imperative — sharp falling tone on "ship".' },
  },
  {
    word: 'four beds in this room',
    ipa: '/fɔːr bɛdz ɪn ðɪs ruːm/',
    level: 'easy',
    type: 'phrase',
    source: 'seed',
    reviewed: true,
    targets: ['f', 'ɔː', 'ɛ', 'z', 'ð'],
    phonemic: { tag: 'consonant-cluster', detail: '/bɛdz/ has final voiced /z/ allomorph of plural -s; /ð/ in "this"; /ɔː/ in "four".' },
    syllabic: { tag: 'five-word', detail: '"four", "beds", "room" carry stress; "in" and "this" reduce.' },
    accentual: { tag: 'end-focus', detail: 'Nuclear stress on "room"; "four" and "beds" share secondary stress.' },
    intonational: { tag: 'falling', detail: 'Declarative — falling nucleus on "room".' },
  },

  // ── MEDIUM PHRASES ────────────────────────────────────────────────────────
  {
    word: 'together we can decide',
    ipa: '/təˈɡɛð.ər wi kən dɪˈsaɪd/',
    level: 'medium',
    type: 'phrase',
    source: 'seed',
    reviewed: true,
    targets: ['ð', 'ɛ', 'ər', 'aɪ'],
    phonemic: { tag: 'medial-dental-diphthong', detail: '/ð/ in "together"; /aɪ/ diphthong in "decide"; /ər/ schwa-r coda.' },
    syllabic: { tag: 'five-word', detail: '"together" (3 syllables) and "decide" (2) carry stress; "we" and "can" reduce.' },
    accentual: { tag: 'end-focus', detail: 'Nuclear stress on "decide"; secondary on /ɡɛð/ in "together".' },
    intonational: { tag: 'falling', detail: 'Statement with confidence — falling nucleus on "decide".' },
  },
  {
    word: 'it is very important',
    ipa: '/ɪt ɪz ˈvɛr.i ɪmˈpɔːr.tənt/',
    level: 'medium',
    type: 'phrase',
    source: 'seed',
    reviewed: true,
    targets: ['ɪ', 'v', 'ɛ', 'ɔː', 'nt'],
    phonemic: { tag: 'linking', detail: 'Linking /t/ in "it is" may flap to [ɾ]; /v/ fricative in "very"; /ɔːr/ rhotic vowel.' },
    syllabic: { tag: 'four-word', detail: '"it" and "is" reduce; "very" and "important" carry full stress.' },
    accentual: { tag: 'end-focus', detail: 'Nuclear stress on /pɔːr/ in "important".' },
    intonational: { tag: 'falling', detail: 'Emphatic statement — wide falling tone on "important".' },
  },
  {
    word: 'because of the garden',
    ipa: '/bɪˈkɒz əv ðə ˈɡɑːr.dən/',
    level: 'medium',
    type: 'phrase',
    source: 'seed',
    reviewed: true,
    targets: ['ɪ', 'ɒ', 'z', 'ə', 'ɑː'],
    phonemic: { tag: 'function-reduction', detail: '"of" reduces to /əv/; "the" to /ðə/; /ɒ/ in "because"; long /ɑː/ in "garden".' },
    syllabic: { tag: 'four-word', detail: '"because" and "garden" stressed; "of" and "the" fully reduced.' },
    accentual: { tag: 'end-focus', detail: 'Nuclear stress on "garden" first syllable /ɡɑːr/.' },
    intonational: { tag: 'rising-falling', detail: 'Prepositional phrase — may carry rise-fall if used contrastively.' },
  },

  // ── HARD PHRASES ──────────────────────────────────────────────────────────
  {
    word: 'particularly important pronunciation',
    ipa: '/pərˈtɪk.jə.lər.li ɪmˈpɔːr.tənt prəˌnʌn.siˈeɪ.ʃən/',
    level: 'hard',
    type: 'phrase',
    source: 'seed',
    reviewed: true,
    targets: ['ə', 'ɪk', 'ɔː', 'ʌ', 'eɪ', 'ʃ'],
    phonemic: { tag: 'polysyllabic-chain', detail: 'Three polysyllabic words in a row; multiple schwa reductions; /eɪ/ diphthong in "pronunciation".' },
    syllabic: { tag: 'thirteen-syllable', detail: 'pər.ˈtɪk.jə.lər.li (5) + ɪm.ˈpɔːr.tənt (3) + prə.ˌnʌn.si.ˈeɪ.ʃən (5) = 13 syllables.' },
    accentual: { tag: 'three-nucleus', detail: 'Three separate primary stresses: /tɪk/, /pɔːr/, /eɪ/.' },
    intonational: { tag: 'falling', detail: 'Final nucleus on /eɪ/ in "pronunciation" with falling tail.' },
  },
  {
    word: 'the entrepreneur will simultaneously deteriorate',
    ipa: '/ðə ˌɒn.trə.prəˈnɜːr wɪl ˌsɪm.əlˈteɪ.ni.əs.li dɪˈtɪər.i.ə.reɪt/',
    level: 'hard',
    type: 'phrase',
    source: 'seed',
    reviewed: true,
    targets: ['ɒ', 'nɜː', 'teɪ', 'ɪər', 'reɪ'],
    phonemic: { tag: 'advanced-polysyllabic', detail: 'Four content words with complex stress; /nɜːr/ r-coloured vowel; adjacent vowels in "deteriorate".' },
    syllabic: { tag: 'sixteen-syllable', detail: 'ðə(1) + ˌɒn.trə.prəˈnɜːr(5) + wɪl(1) + ˌsɪm.əlˈteɪ.ni.əs.li(6) + dɪˈtɪər.i.ə.reɪt(5) = 18 syllables.' },
    accentual: { tag: 'four-nucleus', detail: 'Primary stresses on /nɜːr/, /teɪ/, /tɪər/ — maintain rhythm across long utterance.' },
    intonational: { tag: 'falling', detail: 'Long declarative — final falling nucleus on /reɪt/ in "deteriorate".' },
  },
];

async function insertEntry(w) {
  await db.query(
    `INSERT INTO words
       (word, ipa, level, type, source, reviewed, targets,
        phonemic, syllabic, accentual, intonational)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
     ON CONFLICT (word) DO NOTHING`,
    [
      w.word,
      w.ipa,
      w.level,
      w.type || 'word',
      w.source,
      w.reviewed,
      w.targets,
      JSON.stringify(w.phonemic),
      JSON.stringify(w.syllabic),
      JSON.stringify(w.accentual),
      JSON.stringify(w.intonational),
    ],
  );
  console.log(`  ✓ [${w.type || 'word'}] ${w.word}`);
}

async function seed() {
  console.log('Seeding words…');
  for (const w of seedWords)   await insertEntry(w);
  console.log('Seeding phrases…');
  for (const w of seedPhrases) await insertEntry(w);
  console.log('Done.');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
