require('dotenv').config();
const db = require('./index');

const seedWords = [
  // ── EASY ──────────────────────────────────────────────────────────────────
  {
    word: 'the',
    ipa: '/ðə/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['ð'],
    phonemic: { tag: 'function-word', detail: 'Definite article; unstressed schwa form /ðə/ before consonants.' },
    syllabic: { tag: 'monosyllabic', detail: 'Single syllable — no syllable boundary.' },
    accentual: { tag: 'unstressed', detail: 'Typically unstressed in a sentence; receives no primary stress.' },
    intonational: { tag: 'neutral', detail: 'No independent intonation contour; part of larger NP.' },
  },
  {
    word: 'ship',
    ipa: '/ʃɪp/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['ʃ', 'ɪ'],
    phonemic: { tag: 'minimal-pair', detail: 'Contrasts with "sheep" /ʃiːp/; short /ɪ/ vs long /iː/ is a common ESL error.' },
    syllabic: { tag: 'monosyllabic', detail: 'CVC structure; single closed syllable.' },
    accentual: { tag: 'stressed', detail: 'Single syllable receives full stress.' },
    intonational: { tag: 'falling', detail: 'Falling intonation when used as an isolated noun.' },
  },
  {
    word: 'bed',
    ipa: '/bɛd/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['ɛ'],
    phonemic: { tag: 'vowel-quality', detail: 'Mid-front /ɛ/; confused with /æ/ (bad) or /ɪ/ (bid) by many learners.' },
    syllabic: { tag: 'monosyllabic', detail: 'CVC; short vowel in a closed syllable.' },
    accentual: { tag: 'stressed', detail: 'Full primary stress on the single syllable.' },
    intonational: { tag: 'falling', detail: 'Falling nuclear tone in isolation or sentence-final position.' },
  },
  {
    word: 'this',
    ipa: '/ðɪs/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['ð', 'ɪ'],
    phonemic: { tag: 'voiced-dental', detail: 'Voiced dental fricative /ð/ is absent in many L1s; often replaced by /d/ or /z/.' },
    syllabic: { tag: 'monosyllabic', detail: 'Single closed syllable CCVC.' },
    accentual: { tag: 'variable', detail: 'Can be stressed (contrastive "THIS one") or unstressed in a phrase.' },
    intonational: { tag: 'neutral', detail: 'Typically part of a larger NP; no independent contour.' },
  },
  {
    word: 'run',
    ipa: '/rʌn/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['r', 'ʌ'],
    phonemic: { tag: 'approximant', detail: 'English /r/ is a retroflex approximant; /ʌ/ is a mid-central-back vowel distinct from /ɑ/ or /ʊ/.' },
    syllabic: { tag: 'monosyllabic', detail: 'CVC closed syllable.' },
    accentual: { tag: 'stressed', detail: 'Full stress on single syllable.' },
    intonational: { tag: 'falling', detail: 'Falling intonation as a verb in isolation.' },
  },
  {
    word: 'four',
    ipa: '/fɔːr/',
    level: 'easy',
    source: 'seed',
    reviewed: true,
    targets: ['f', 'ɔː'],
    phonemic: { tag: 'rhotic-vowel', detail: '/ɔːr/ is an r-coloured vowel; non-rhotic learners may drop the /r/ coda.' },
    syllabic: { tag: 'monosyllabic', detail: 'Single syllable with long vowel.' },
    accentual: { tag: 'stressed', detail: 'Fully stressed in isolation; may reduce in fast speech numerals.' },
    intonational: { tag: 'falling', detail: 'Falling when listing numbers or in isolation.' },
  },

  // ── MEDIUM ────────────────────────────────────────────────────────────────
  {
    word: 'butter',
    ipa: '/ˈbʌt.ər/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['ʌ', 't', 'ər'],
    phonemic: { tag: 'flap-allophone', detail: 'Intervocalic /t/ is realised as a flap [ɾ] in American English; schwa /ər/ in unstressed syllable.' },
    syllabic: { tag: 'disyllabic', detail: 'Two syllables: ˈbʌt.ər — primary stress on first.' },
    accentual: { tag: 'trochaic', detail: 'Strong-weak stress pattern (trochee).' },
    intonational: { tag: 'falling', detail: 'Falling nuclear tone on the stressed syllable in isolation.' },
  },
  {
    word: 'decide',
    ipa: '/dɪˈsaɪd/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['dɪ', 'saɪ'],
    phonemic: { tag: 'diphthong', detail: '/aɪ/ diphthong; unstressed first syllable /dɪ/ often deleted by learners.' },
    syllabic: { tag: 'disyllabic', detail: 'Two syllables: dɪ.ˈsaɪd — stress on second.' },
    accentual: { tag: 'iambic', detail: 'Weak-strong pattern (iamb); first syllable reduced.' },
    intonational: { tag: 'falling', detail: 'Nuclear fall on the stressed /saɪ/ syllable.' },
  },
  {
    word: 'garden',
    ipa: '/ˈɡɑːr.dən/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['ɑː', 'ə'],
    phonemic: { tag: 'open-back', detail: 'Long /ɑː/ in first syllable; unstressed schwa /ə/ in the final syllable.' },
    syllabic: { tag: 'disyllabic', detail: 'ˈɡɑːr.dən — primary stress on first syllable.' },
    accentual: { tag: 'trochaic', detail: 'Strong-weak stress pattern.' },
    intonational: { tag: 'falling', detail: 'Falling nuclear tone on stressed syllable.' },
  },
  {
    word: 'because',
    ipa: '/bɪˈkɒz/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['bɪ', 'ɒ', 'z'],
    phonemic: { tag: 'voiced-fricative', detail: 'Final /z/; /ɒ/ is a short open-back rounded vowel absent in many L1s.' },
    syllabic: { tag: 'disyllabic', detail: 'bɪ.ˈkɒz — stress on second syllable.' },
    accentual: { tag: 'iambic', detail: 'Unstressed first syllable /bɪ/ often reduced further to /bə/.' },
    intonational: { tag: 'rising-falling', detail: 'Often carries a complex tone in mid-clause position.' },
  },
  {
    word: 'together',
    ipa: '/təˈɡɛð.ər/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['ð', 'ɛ', 'ər'],
    phonemic: { tag: 'medial-dental', detail: '/ð/ in medial position; /ɛ/ mid-front vowel; schwa coda /ər/.' },
    syllabic: { tag: 'trisyllabic', detail: 'tə.ˈɡɛð.ər — three syllables, stress on second.' },
    accentual: { tag: 'iambic-extended', detail: 'Weak-strong-weak pattern; primary stress on /ɡɛð/.' },
    intonational: { tag: 'falling', detail: 'Nuclear fall on the stressed syllable.' },
  },
  {
    word: 'important',
    ipa: '/ɪmˈpɔːr.tənt/',
    level: 'medium',
    source: 'seed',
    reviewed: true,
    targets: ['ɪm', 'ɔː', 'r', 'nt'],
    phonemic: { tag: 'nasal-cluster', detail: '/nt/ word-final cluster; /ɔːr/ rhotic vowel; /ɪm/ unstressed onset.' },
    syllabic: { tag: 'trisyllabic', detail: 'ɪm.ˈpɔːr.tənt — three syllables, stress on second.' },
    accentual: { tag: 'secondary', detail: 'Weak-strong-weak; possible secondary stress on first syllable in slow speech.' },
    intonational: { tag: 'falling', detail: 'Main nuclear stress falls on /pɔːr/.' },
  },

  // ── HARD ──────────────────────────────────────────────────────────────────
  {
    word: 'particularly',
    ipa: '/pərˈtɪk.jə.lər.li/',
    level: 'hard',
    source: 'seed',
    reviewed: true,
    targets: ['ə', 'ɪk', 'jə', 'l'],
    phonemic: { tag: 'polysyllabic-reduction', detail: 'Five-syllable word; multiple unstressed schwas; /j/ glide before /ə/.' },
    syllabic: { tag: 'pentasyllabic', detail: 'pər.ˈtɪk.jə.lər.li — five syllables, primary stress on second.' },
    accentual: { tag: 'complex', detail: 'Stress on /tɪk/; remaining syllables all weakly reduced.' },
    intonational: { tag: 'falling', detail: 'Nuclear tone lands on the stressed syllable /tɪk/.' },
  },
  {
    word: 'deteriorate',
    ipa: '/dɪˈtɪər.i.ə.reɪt/',
    level: 'hard',
    source: 'seed',
    reviewed: true,
    targets: ['ɪər', 'i', 'ə', 'reɪ'],
    phonemic: { tag: 'vowel-sequence', detail: 'Adjacent vowel sounds /ɪər.i.ə/ require careful articulation; /reɪ/ diphthong before final /t/.' },
    syllabic: { tag: 'pentasyllabic', detail: 'dɪ.ˈtɪər.i.ə.reɪt — five syllables, stress on second.' },
    accentual: { tag: 'iambic', detail: 'Stress on /tɪər/; multiple unstressed syllables follow.' },
    intonational: { tag: 'falling', detail: 'Nuclear fall on the stressed syllable.' },
  },
  {
    word: 'entrepreneurship',
    ipa: '/ˌɒn.trə.prəˈnɜːr.ʃɪp/',
    level: 'hard',
    source: 'seed',
    reviewed: true,
    targets: ['ɒ', 'ə', 'nɜː', 'ʃ'],
    phonemic: { tag: 'secondary-stress', detail: 'Secondary stress on /ɒn/; primary on /nɜːr/; /ʃɪp/ suffix; multiple schwas.' },
    syllabic: { tag: 'pentasyllabic', detail: 'ˌɒn.trə.prə.ˈnɜːr.ʃɪp — five syllables.' },
    accentual: { tag: 'double-stress', detail: 'Primary stress on /nɜːr/, secondary on /ɒn/ at the onset.' },
    intonational: { tag: 'falling', detail: 'Nuclear tone on the primary-stressed syllable /nɜːr/.' },
  },
  {
    word: 'simultaneously',
    ipa: '/ˌsɪm.əlˈteɪ.ni.əs.li/',
    level: 'hard',
    source: 'seed',
    reviewed: true,
    targets: ['ɪ', 'teɪ', 'ni', 'əs'],
    phonemic: { tag: 'polysyllabic-diphthong', detail: 'Six syllables; /teɪ/ diphthong carries primary stress; multiple vowel reductions.' },
    syllabic: { tag: 'hexasyllabic', detail: 'ˌsɪm.əl.ˈteɪ.ni.əs.li — six syllables.' },
    accentual: { tag: 'double-stress', detail: 'Primary stress on /teɪ/, secondary on /sɪm/.' },
    intonational: { tag: 'falling', detail: 'Nuclear accent on /teɪ/.' },
  },
  {
    word: 'pronunciation',
    ipa: '/prəˌnʌn.siˈeɪ.ʃən/',
    level: 'hard',
    source: 'seed',
    reviewed: true,
    targets: ['ə', 'ʌ', 'eɪ', 'ʃ'],
    phonemic: { tag: 'vowel-shift', detail: 'Common learner error: pronouncing as "pronounciation"; /ʌ/ in second syllable; /eɪ/ nucleus; /ʃ/ before /ən/.' },
    syllabic: { tag: 'pentasyllabic', detail: 'prə.ˌnʌn.si.ˈeɪ.ʃən — five syllables, stress on fourth.' },
    accentual: { tag: 'secondary', detail: 'Secondary stress on /nʌn/, primary on /eɪ/.' },
    intonational: { tag: 'falling', detail: 'Nuclear fall on /eɪ/ syllable.' },
  },
];

async function seed() {
  console.log('Seeding words table…');
  for (const w of seedWords) {
    await db.query(
      `INSERT INTO words
         (word, ipa, level, source, reviewed, targets,
          phonemic, syllabic, accentual, intonational)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
       ON CONFLICT (word) DO NOTHING`,
      [
        w.word,
        w.ipa,
        w.level,
        w.source,
        w.reviewed,
        w.targets,
        JSON.stringify(w.phonemic),
        JSON.stringify(w.syllabic),
        JSON.stringify(w.accentual),
        JSON.stringify(w.intonational),
      ],
    );
    console.log(`  ✓ ${w.word}`);
  }
  console.log('Done.');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
